#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'
ruby_requirement = Gem::Dependency.new('', ['~> 2.6', '>=2.6.1'])

fail 'Specify a path to your new project' unless ARGV.length == 1
unless ruby_requirement.match?('', RUBY_VERSION)
  fail "Install and use a supported version of ruby #{ruby_requirement}"
end

outpath = Pathname(ENV['PWD']).join(ARGV[0]).expand_path

outpath.mkdir unless outpath.directory?

outpath.join('BSGemfile').open('w') do |gf|
  gf.write <<~GEMFILE
    # Temporary Gemfile

    source 'https://rubygems.org'
    gem 'middleman', '~> 4.2'
  GEMFILE
end

Dir.chdir(outpath) do
  system 'bundle install --quiet --gemfile=BSGemfile'
  system 'bundle exec --gemfile=BSGemfile middleman init -B -T werebus/wobsite'
end
