#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'
ruby_requirement = Gem::Dependency.new('', ['~> 2.6', '>=2.6.1'])

fail 'Specify a path to your new project' unless ARGV.length == 1
unless ruby_requirement.match?('', RUBY_VERSION)
  fail "Install and use a supported version of ruby #{ruby_requirement}"
end

outpath = Pathname(ENV['PWD']).join(ARGV[0]).expand_path

outpath.mkdir unless outpath.directory?

Dir.chdir(outpath) do
  system 'gem install middleman --silent'
  system 'middleman init --template --skip-bundle werebus/wobsite'
end
